name = "dead-simple"
license = "MIT"
licenselink = "https://github.com/barklan/hugo-dead-simple/blob/main/LICENSE"
description = "Dead simple Hugo theme."
homepage = "https://github.com/barklan/hugo-dead-simple"
tags = [
    "blog",
    "company",
    "documentation",
    "docs",
    "minimal",
    "responsive",
    "light",
    "simple",
    "clean"
]
features = [
  "responsive",
  "single-column",
  "blog",
  "table-of-contents",
  "favicon"
]
min_version = "0.83.0"

[author]
    name = "Gleb Buzin"
    homepage = "https://github.com/barklan"
